export const allBooks = [
    {id: 1, name: "To Kill a Mockingbird", author: "Harper Lee", cover: "./materials/img/bookCovers/To Kill a Mockingbird.jpg", price: 10.99, description: "A novel about racial injustice and childhood innocence in the Deep South."},
    {id: 2, name: "1984", author: "George Orwell", cover: "./materials/img/bookCovers/1984.jpg", price: 9.99, description: "A dystopian novel exploring the dangers of totalitarianism and extreme political ideology."},
    {id: 3, name: "Pride and Prejudice", author: "Jane Austen", cover: "./materials/img/bookCovers/Pride and Prejudice.jpg", price: 12.50, description: "A classic novel of manners and social status in 19th-century England."},
    {id: 4, name: "The Great Gatsby", author: "F. Scott Fitzgerald", cover: "./materials/img/bookCovers/The Great Gatsby.jpg", price: 14.00, description: "A story of wealth, love, and the American Dream set in the Jazz Age."},
    {id: 5, name: "Moby-Dick", author: "Herman Melville", cover: "./materials/img/bookCovers/Moby Dick.jpg", price: 11.75, description: "An epic tale of obsession and adventure on the high seas."},
    {id: 6, name: "The Catcher in the Rye", author: "J.D. Salinger", cover: "./materials/img/bookCovers/The Catcher in the Rye.jpg", price: 13.25, description: "A novel about adolescent angst and rebellion."},
    {id: 7, name: "The Hobbit", author: "J.R.R. Tolkien", cover: "./materials/img/bookCovers/The Hobbit.jpg", price: 15.00, description: "A fantasy adventure that introduces readers to Middle-earth."},
    {id: 8, name: "Harry Potter and the Sorcerer's Stone", author: "J.K. Rowling", cover: "./materials/img/bookCovers/Harry Potter and the Sorcerer's Stone.jpg", price: 19.99, description: "The first book in the beloved series about a young wizard's journey."},
    {id: 9, name: "The Lord of the Rings", author: "J.R.R. Tolkien", cover: "./materials/img/bookCovers/The Lord of the Rings The Fellowship of the Ring.jpg", price: 22.50, description: "The beginning of the epic fantasy trilogy that follows the quest to destroy a powerful ring."},
    {id: 10, name: "Brave New World", author: "Aldous Huxley", cover: "./materials/img/bookCovers/Brave New World.jpg", price: 12.99, description: "A dystopian vision of a future society driven by technology and conformity."},
    {id: 11, name: "Fahrenheit 451", author: "Ray Bradbury", cover: "./materials/img/bookCovers/Fahrenheit 451.jpg", price: 14.25, description: "A novel about a future society where books are banned and 'firemen' burn any that are found."},
    {id: 12, name: "Jane Eyre", author: "Charlotte Brontë", cover: "./materials/img/bookCovers/Jane Eyre.jpg", price: 13.75, description: "A classic novel about a strong-willed orphan's journey to self-respect and love."},
    {id: 13, name: "Wuthering Heights", author: "Emily Brontë", cover: "./materials/img/bookCovers/Wuthering Heights.jpg", price: 15.50, description: "A dark and passionate story of love and revenge set on the Yorkshire moors."},
    {id: 14, name: "The Alchemist", author: "Paulo Coelho", cover: "./materials/img/bookCovers/The Alchemist.jpg", price: 16.00, description: "A philosophical book about a shepherd's quest to realize his personal legend."},
    {id: 15, name: "The Da Vinci Code", author: "Dan Brown", cover: "./materials/img/bookCovers/The Da Vinci Code.jpg", price: 18.75, description: "A gripping thriller that combines art, history, and conspiracy."},
    {id: 16, name: "Gone with the Wind", author: "Margaret Mitchell", cover: "./materials/img/bookCovers/Gone with the Wind.jpg", price: 20.00, description: "A sweeping historical novel set during the American Civil War and Reconstruction era."},
    {id: 17, name: "The Shining", author: "Stephen King", cover: "./materials/img/bookCovers/The Shining.jpg", price: 17.50, description: "A chilling horror novel about a family isolated in a haunted hotel."},
    {id: 18, name: "11/22/63", author: "Stephen King", cover: "./materials/img/bookCovers/221163.jpg", price: 16.4},
    {id: 19, name: "The Girl with the Dragon Tattoo", author: "Stieg Larsson", cover: "./materials/img/bookCovers/The Girl with the Dragon Tattoo.jpg", price: 16.75, description: "A gripping crime novel involving a missing person case and a journalist's investigation."},
    {id: 20, name: "Life of Pi", author: "Yann Martel", cover: "./materials/img/bookCovers/Life of Pi.jpg", price: 14.50, description: "A fantastical adventure story of a boy stranded on a lifeboat with a Bengal tiger."},
    {id: 21, name: "Little Women", author: "Louisa May Alcott", cover: "./materials/img/bookCovers/Little Women.jpg", price: 13.00, description: "A beloved classic about the lives and trials of the four March sisters."},
    {id: 22, name: "Murder on the Orient Express", author: "Agatha Christie", cover: "./materials/img/bookCovers/Murder on the Orient Express.jpg", price: 15.25, description: "A classic detective novel featuring Hercule Poirot solving a murder on a luxury train."},
    {id: 23, name: "The Road", author: "Cormac McCarthy", cover: "./materials/img/bookCovers/The Road.jpg", price: 17.00, description: "A stark, haunting story of a father and son journeying through a post-apocalyptic landscape."},
    {id: 24, name: "Catch-22", author: "Joseph Heller", cover: "./materials/img/bookCovers/Catch-22.jpg", price: 16.50, description: "A satirical novel about the absurdities of war and bureaucracy."},
    {id: 25, name: "The Hitchhiker's Guide to the Galaxy", author: "Douglas Adams", cover: "./materials/img/bookCovers/The Hitchhiker's Guide to the Galaxy.jpg", price: 14.99, description: "A comedic science fiction adventure across the galaxy."},
    {id: 26, name: "A Game of Thrones", author: "George R.R. Martin", cover: "./materials/img/bookCovers/A Game of Thrones.jpg", price: 19.99, description: "The first book in the epic fantasy series 'A Song of Ice and Fire'."},
    {id: 27, name: "The Martian", author: "Andy Weir", cover: "./materials/img/bookCovers/The Martian.jpg", price: 18.25, description: "A gripping tale of survival and ingenuity on Mars."},
    {id: 28, name: "Dune", author: "Frank Herbert", cover: "./materials/img/bookCovers/Dune.jpg", price: 22.00, description: "A science fiction masterpiece about politics, religion, and survival on a desert planet."},
    {id: 29, name: "The Count of Monte Cristo", author: "Alexandre Dumas", cover: "./materials/img/bookCovers/The Count of Monte Cristo.jpg", price: 16.75, description: "A classic adventure novel of betrayal, revenge, and redemption."},
    {id: 30, name: "One Hundred Years of Solitude", author: "Gabriel García Márquez", cover: "./materials/img/bookCovers/One Hundred Years of Solitude.jpg", price: 17.50, description: "A landmark in magical realism telling the story of the Buendía family over several generations."},
];

export const bestsellersBooks = [
    {id: 2, name: "1984", author: "George Orwell", cover: "./materials/img/bookCovers/1984.jpg", price: 9.99, description: "A dystopian novel exploring the dangers of totalitarianism and extreme political ideology."},
    {id: 11, name: "Fahrenheit 451", author: "Ray Bradbury", cover: "./materials/img/bookCovers/Fahrenheit 451.jpg", price: 14.25, description: "A novel about a future society where books are banned and 'firemen' burn any that are found."},
    {id: 17, name: "The Shining", author: "Stephen King", cover: "./materials/img/bookCovers/The Shining.jpg", price: 17.50, description: "A chilling horror novel about a family isolated in a haunted hotel."},
    {id: 27, name: "The Martian", author: "Andy Weir", cover: "./materials/img/bookCovers/The Martian.jpg", price: 18.25, description: "A gripping tale of survival and ingenuity on Mars."},
    {id: 8, name: "Harry Potter and the Sorcerer's Stone", author: "J.K. Rowling", cover: "./materials/img/bookCovers/Harry Potter and the Sorcerer's Stone.jpg", price: 19.99, description: "The first book in the beloved series about a young wizard's journey."},
    {id: 22, name: "Murder on the Orient Express", author: "Agatha Christie", cover: "./materials/img/bookCovers/Murder on the Orient Express.jpg", price: 15.25, description: "A classic detective novel featuring Hercule Poirot solving a murder on a luxury train."},
    {id: 9, name: "The Lord of the Rings", author: "J.R.R. Tolkien", cover: "./materials/img/bookCovers/The Lord of the Rings The Fellowship of the Ring.jpg", price: 22.50, description: "The beginning of the epic fantasy trilogy that follows the quest to destroy a powerful ring."},
    {id: 28, name: "Dune", author: "Frank Herbert", cover: "./materials/img/bookCovers/Dune.jpg", price: 22.00, description: "A science fiction masterpiece about politics, religion, and survival on a desert planet."},
    
    {id: 20, name: "Life of Pi", author: "Yann Martel", cover: "./materials/img/bookCovers/Life of Pi.jpg", price: 14.50, description: "A fantastical adventure story of a boy stranded on a lifeboat with a Bengal tiger."},
    {id: 23, name: "The Road", author: "Cormac McCarthy", cover: "./materials/img/bookCovers/The Road.jpg", price: 17.00, description: "A stark, haunting story of a father and son journeying through a post-apocalyptic landscape."},
];

export const classicBooks = [
    {id: 12, name: "Jane Eyre", author: "Charlotte Brontë", cover: "./materials/img/bookCovers/Jane Eyre.jpg", price: 13.75, description: "A classic novel about a strong-willed orphan's journey to self-respect and love."},
    {id: 5, name: "Moby-Dick", author: "Herman Melville", cover: "./materials/img/bookCovers/Moby Dick.jpg", price: 11.75, description: "An epic tale of obsession and adventure on the high seas."},
    {id: 3, name: "Pride and Prejudice", author: "Jane Austen", cover: "./materials/img/bookCovers/Pride and Prejudice.jpg", price: 12.50, description: "A classic novel of manners and social status in 19th-century England."},
    {id: 15, name: "The Da Vinci Code", author: "Dan Brown", cover: "./materials/img/bookCovers/The Da Vinci Code.jpg", price: 18.75, description: "A gripping thriller that combines art, history, and conspiracy."},
    {id: 21, name: "Little Women", author: "Louisa May Alcott", cover: "./materials/img/bookCovers/Little Women.jpg", price: 13.00, description: "A beloved classic about the lives and trials of the four March sisters."},
    {id: 4, name: "The Great Gatsby", author: "F. Scott Fitzgerald", cover: "./materials/img/bookCovers/The Great Gatsby.jpg", price: 14.00, description: "A story of wealth, love, and the American Dream set in the Jazz Age."},
    {id: 29, name: "The Count of Monte Cristo", author: "Alexandre Dumas", cover: "./materials/img/bookCovers/The Count of Monte Cristo.jpg", price: 16.75, description: "A classic adventure novel of betrayal, revenge, and redemption."},
    {id: 30, name: "One Hundred Years of Solitude", author: "Gabriel García Márquez", cover: "./materials/img/bookCovers/One Hundred Years of Solitude.jpg", price: 17.50, description: "A landmark in magical realism telling the story of the Buendía family over several generations."},
    
    {id: 13, name: "Wuthering Heights", author: "Emily Brontë", cover: "./materials/img/bookCovers/Wuthering Heights.jpg", price: 15.50, description: "A dark and passionate story of love and revenge set on the Yorkshire moors."},
    {id: 6, name: "The Catcher in the Rye", author: "J.D. Salinger", cover: "./materials/img/bookCovers/The Catcher in the Rye.jpg", price: 13.25, description: "A novel about adolescent angst and rebellion."},
];